### ISSUE TITLE
Keys are not being set by default format.

### ISSUE THREAD

**Issue by shroy** [xxRockOnxx/vue2-timepicker#13] opened 2017-12-05 17:59 UTC
I just migrated from the original repo to use yours. I have a very simple setup in which my *v-model* now gives me the error message: `Invalid prop: type check failed for prop "value". Expected Object, got Null.`

```html
<template lang='pug'>
    ...
    vue-timepicker(v-model="time_spent", :minute-interval="15")
</template>

<script>
  import VueTimepicker from 'vue2-timepicker'

  export default {
    components: { VueTimepicker },
    data: () => ({
      time_spent: {}
    }),
   ....
</script>
```

If I explicitly bind the value prop, I no longer receive error message..
`vue-timepicker(:value="time_spent", :minute-interval="15")`

Btw - thank you for maintaining this project!

**Comment by xxRockOnxx** [comment] 2017-12-05 20:15
`v-model` is actually just passing `:value` to a component and automatically updating it when it receives an `input` event.

The component is not doing any extra checks, that's just core Vue prop validation.

See https://github.com/xxRockOnxx/vue2-timepicker/blob/master/src/vue-timepicker.vue#L13

**Comment by shroy** [comment] 2017-12-06 18:47
I did copy the example above and it appeared the original error message posted was misleading and can be ignored as I had a function that was resetting my value. 

However, I am still unable to receive the expected return value using the components default values. It appears the issue is the default format being set in the props is not working. If the v-model object does not have any keys, then it does not update any fields.

https://github.com/xxRockOnxx/vue2-timepicker/blob/master/src/vue-timepicker.vue#L22

**Comment by xxRockOnxx** [comment] 2017-12-06 19:56
yea, it should have the keys set by the format.

**Comment by xxRockOnxx** [comment] 2017-12-08 05:39
@shroy can you also confirm so I can close the issue? or if you still have problems so I can make a fix?

**Comment by shroy** [comment] 2017-12-08 17:27
@xxRockOnxx - The issue is still there. I updated the title of this ticket to better reflect it.

**Comment by xxRockOnxx** [comment] 2017-12-11 10:00
can you give me an example so I can reproduce it and make a fix?

**Comment by shroy** [comment] 2017-12-11 20:43
Simply installing vue2-timepicker and setting it up like the example above, should reproduce it. 

Keys are not being set by the default formatter in the object specified in `v-model`, so *time_spent* does not populate with the selected input. This will not work..

```
<template>
  div
    vue-timepicker(v-model="time_spent")
</template>

<script>
  import VueTimepicker from 'vue2-timepicker'

  export default {
    components: { VueTimepicker },
    data: () => ({
      time_spent: {}
    })
</script>
```

However, explicitly providing the keys **does** work..

```
    data: () => ({
      time_spent: {
        HH: '',
        mm: ''
      }
    })
```

Let me know if you need more info. If you'd prefer, I can find time to provide a pull requests with a potential fix.

**Comment by xxRockOnxx** [comment] 2017-12-12 10:09
I think I already answered that: https://github.com/xxRockOnxx/vue2-timepicker/issues/13#issuecomment-349756224

Anyway, it's fine if you submit a PR if you think it'll improve the package :)

**Comment by xxRockOnxx** [comment] 2017-12-16 06:57
Closing because no response and question is answered.

**Closed by xxRockOnxx** 2017-12-16 06:57 UTC
